name: mg-motionllm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytorch=2.2.0
  - pytorch-cuda=11.8
  - torchvision
  - cudatoolkit=11.8
  - pip
  - ffmpeg
  - numpy
  - scipy
  - scikit-learn
  - h5py
  - trimesh
  - shapely
  - pip:
      - einops
      - transformers==4.28.1
      - accelerate
      - sentencepiece
      - ftfy
      - smplx
      - opencv-python
      - imageio
      - git+https://github.com/openai/CLIP.git
      - bert-score
      - rouge-score
      - nltk
      #- nlg-eval
      - nlg-metricverse
      - spacy==3.7.4
      - pyarrow==12.0.1
      - websockets
